/**
 * Below are the color palettes used in the app. Each named theme defines the full
 * set of semantic colors consumed via useThemeColor/ThemedText/ThemedView.
 */

import { Platform } from 'react-native';

/**
 * Eye-comfort palette set. Ratio guide per theme: 60% background, 25% card/surface,
 * 8% primary CTA, 4% border/divider, 3% status accent. Avoids pure black/white.
 */
export const Colors = {
  softPaperLight: {
    text: '#253248',
    background: '#F6F7F9',
    tint: '#5A6BD8',
    icon: '#6A7A90',
    tabIconDefault: '#6A7A90',
    tabIconSelected: '#5A6BD8',
    success: '#37946B',
    danger: '#C86A6A',
    warning: '#C08A2E',
    muted: '#6A7A90',
    border: '#E5E9F0',
    card: '#FCFDFF',
    missedTint: '#EFE0E2',
    completedTint: '#D7E7E2',
    partiallyCompletedTint: '#ECE3D4',
    categoryFallback: '#6A7A90',
  },
  sageCalmLight: {
    text: '#24352C',
    background: '#F2F6F2',
    tint: '#4A7A61',
    icon: '#69806F',
    tabIconDefault: '#69806F',
    tabIconSelected: '#4A7A61',
    success: '#2F8A5C',
    danger: '#C56D6D',
    warning: '#B8860B',
    muted: '#69806F',
    border: '#DFE9E2',
    card: '#FBFDFB',
    missedTint: '#EBE0DD',
    completedTint: '#D3E5DA',
    partiallyCompletedTint: '#E8E2C8',
    categoryFallback: '#69806F',
  },
  oceanMistLight: {
    text: '#1F3A48',
    background: '#F1F6F8',
    tint: '#32708F',
    icon: '#5F7A87',
    tabIconDefault: '#5F7A87',
    tabIconSelected: '#32708F',
    success: '#2F9368',
    danger: '#C97070',
    warning: '#C9A227',
    muted: '#5F7A87',
    border: '#DCEAF1',
    card: '#FAFDFE',
    missedTint: '#EBE1E2',
    completedTint: '#D2E6E1',
    partiallyCompletedTint: '#EAE7D2',
    categoryFallback: '#5F7A87',
  },
  warmOatLight: {
    text: '#372F28',
    background: '#F8F5F0',
    tint: '#A86E4C',
    icon: '#7D7266',
    tabIconDefault: '#7D7266',
    tabIconSelected: '#A86E4C',
    success: '#5F8D66',
    danger: '#C36B5E',
    warning: '#C08A2E',
    muted: '#7D7266',
    border: '#EAE2D7',
    card: '#FFFEFB',
    missedTint: '#F0DFD9',
    completedTint: '#E0E4DA',
    partiallyCompletedTint: '#EEE2CD',
    categoryFallback: '#7D7266',
  },
  lavenderHazeLight: {
    text: '#2F2C44',
    background: '#F6F4FA',
    tint: '#6C69B8',
    icon: '#75718F',
    tabIconDefault: '#75718F',
    tabIconSelected: '#6C69B8',
    success: '#4C9B75',
    danger: '#C67070',
    warning: '#C9A227',
    muted: '#75718F',
    border: '#E6E2F2',
    card: '#FDFCFF',
    missedTint: '#EEDFE4',
    completedTint: '#DBE6E5',
    partiallyCompletedTint: '#EEE5D4',
    categoryFallback: '#75718F',
  },
  slateNightDark: {
    text: '#E7ECF4',
    background: '#12161C',
    tint: '#7AA0F0',
    icon: '#9AA8BA',
    tabIconDefault: '#9AA8BA',
    tabIconSelected: '#7AA0F0',
    success: '#63B48D',
    danger: '#E08A8A',
    warning: '#E3B873',
    muted: '#9AA8BA',
    border: '#2A3441',
    card: '#1B222B',
    missedTint: '#3F3034',
    completedTint: '#243935',
    partiallyCompletedTint: '#443D31',
    categoryFallback: '#9AA8BA',
  },
  deepForestDark: {
    text: '#E4EFE8',
    background: '#101714',
    tint: '#5FAF87',
    icon: '#93A99C',
    tabIconDefault: '#93A99C',
    tabIconSelected: '#5FAF87',
    success: '#66BB93',
    danger: '#DB8C84',
    warning: '#D9C077',
    muted: '#93A99C',
    border: '#243129',
    card: '#18231D',
    missedTint: '#3D312D',
    completedTint: '#233B30',
    partiallyCompletedTint: '#40402C',
    categoryFallback: '#93A99C',
  },
  midnightOceanDark: {
    text: '#E2EBF3',
    background: '#0F1722',
    tint: '#5FA9CB',
    icon: '#8FA5B7',
    tabIconDefault: '#8FA5B7',
    tabIconSelected: '#5FA9CB',
    success: '#5FB592',
    danger: '#DC8B87',
    warning: '#E0BE7A',
    muted: '#8FA5B7',
    border: '#243344',
    card: '#17222F',
    missedTint: '#3C3138',
    completedTint: '#213A3B',
    partiallyCompletedTint: '#413F37',
    categoryFallback: '#8FA5B7',
  },
  warmCharcoalDark: {
    text: '#F0EAE3',
    background: '#171412',
    tint: '#D79A66',
    icon: '#A69C92',
    tabIconDefault: '#A69C92',
    tabIconSelected: '#D79A66',
    success: '#7FB08A',
    danger: '#DB8B7E',
    warning: '#E8C97E',
    muted: '#A69C92',
    border: '#332C27',
    card: '#221E1B',
    missedTint: '#422E2A',
    completedTint: '#2E362C',
    partiallyCompletedTint: '#493F2C',
    categoryFallback: '#A69C92',
  },
  mutedPlumDark: {
    text: '#ECE7F5',
    background: '#171320',
    tint: '#A78BDB',
    icon: '#A89BB8',
    tabIconDefault: '#A89BB8',
    tabIconSelected: '#A78BDB',
    success: '#6FBB93',
    danger: '#DD8CA0',
    warning: '#DDBB7E',
    muted: '#A89BB8',
    border: '#322844',
    card: '#221B2C',
    missedTint: '#432E3C',
    completedTint: '#2A3839',
    partiallyCompletedTint: '#473B37',
    categoryFallback: '#A89BB8',
  },
} as const;

export type ThemeName = keyof typeof Colors;

/** Whether each named theme is a light or dark palette (drives status bar, nav theme, system-preference resolution). */
export const ThemeScheme: Record<ThemeName, 'light' | 'dark'> = {
  softPaperLight: 'light',
  sageCalmLight: 'light',
  oceanMistLight: 'light',
  warmOatLight: 'light',
  lavenderHazeLight: 'light',
  slateNightDark: 'dark',
  deepForestDark: 'dark',
  midnightOceanDark: 'dark',
  warmCharcoalDark: 'dark',
  mutedPlumDark: 'dark',
};

export const THEME_LABELS: Record<ThemeName, string> = {
  softPaperLight: 'Soft Paper Light',
  sageCalmLight: 'Sage Calm Light',
  oceanMistLight: 'Ocean Mist Light',
  warmOatLight: 'Warm Oat Light',
  lavenderHazeLight: 'Lavender Haze Light',
  slateNightDark: 'Slate Night Dark',
  deepForestDark: 'Deep Forest Dark',
  midnightOceanDark: 'Midnight Ocean Dark',
  warmCharcoalDark: 'Warm Charcoal Dark',
  mutedPlumDark: 'Muted Plum Dark',
};

/** Recommended defaults used to resolve the 'system' theme preference. */
export const DEFAULT_LIGHT_THEME: ThemeName = 'softPaperLight';
export const DEFAULT_DARK_THEME: ThemeName = 'slateNightDark';

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
