/**
 * Below are the color palettes used in the app. Each named theme defines the full
 * set of semantic colors consumed via useThemeColor/ThemedText/ThemedView.
 */

import { Platform } from 'react-native';

/**
 * Eye-comfort palette set. Ratio guide per theme: 60% background, 25% card/surface,
 * 8% primary CTA, 4% border/divider, 3% status accent. Avoids pure black/white.
 */
export const Colors = {
  softPaperLight: {
    text: '#253248',
    background: '#F6F7F9',
    tint: '#5A6BD8',
    icon: '#6A7A90',
    tabIconDefault: '#6A7A90',
    tabIconSelected: '#5A6BD8',
    success: '#37946B',
    danger: '#C86A6A',
    warning: '#C08A2E',
    muted: '#6A7A90',
    border: '#E5E9F0',
    card: '#FCFDFF',
    missedTint: '#EFE0E2',
    completedTint: '#D7E7E2',
    partiallyCompletedTint: '#ECE3D4',
    categoryFallback: '#6A7A90',
  },
  sageCalmLight: {
    text: '#24352C',
    background: '#F2F6F2',
    tint: '#4A7A61',
    icon: '#69806F',
    tabIconDefault: '#69806F',
    tabIconSelected: '#4A7A61',
    success: '#2F8A5C',
    danger: '#C56D6D',
    warning: '#B8860B',
    muted: '#69806F',
    border: '#DFE9E2',
    card: '#FBFDFB',
    missedTint: '#EBE0DD',
    completedTint: '#D3E5DA',
    partiallyCompletedTint: '#E8E2C8',
    categoryFallback: '#69806F',
  },
  oceanMistLight: {
    text: '#1F3A48',
    background: '#F1F6F8',
    tint: '#32708F',
    icon: '#5F7A87',
    tabIconDefault: '#5F7A87',
    tabIconSelected: '#32708F',
    success: '#2F9368',
    danger: '#C97070',
    warning: '#C9A227',
    muted: '#5F7A87',
    border: '#DCEAF1',
    card: '#FAFDFE',
    missedTint: '#EBE1E2',
    completedTint: '#D2E6E1',
    partiallyCompletedTint: '#EAE7D2',
    categoryFallback: '#5F7A87',
  },
  warmOatLight: {
    text: '#372F28',
    background: '#F8F5F0',
    tint: '#A86E4C',
    icon: '#7D7266',
    tabIconDefault: '#7D7266',
    tabIconSelected: '#A86E4C',
    success: '#5F8D66',
    danger: '#C36B5E',
    warning: '#C08A2E',
    muted: '#7D7266',
    border: '#EAE2D7',
    card: '#FFFEFB',
    missedTint: '#F0DFD9',
    completedTint: '#E0E4DA',
    partiallyCompletedTint: '#EEE2CD',
    categoryFallback: '#7D7266',
  },
  lavenderHazeLight: {
    text: '#2F2C44',
    background: '#F6F4FA',
    tint: '#6C69B8',
    icon: '#75718F',
    tabIconDefault: '#75718F',
    tabIconSelected: '#6C69B8',
    success: '#4C9B75',
    danger: '#C67070',
    warning: '#C9A227',
    muted: '#75718F',
    border: '#E6E2F2',
    card: '#FDFCFF',
    missedTint: '#EEDFE4',
    completedTint: '#DBE6E5',
    partiallyCompletedTint: '#EEE5D4',
    categoryFallback: '#75718F',
  },
  // "Midnight Blue" — recommended default dark theme: modern, clean, comfortable for long sessions.
  slateNightDark: {
    text: '#E6EDF7',
    background: '#0B1220',
    tint: '#38BDF8',
    icon: '#94A3B8',
    tabIconDefault: '#94A3B8',
    tabIconSelected: '#38BDF8',
    success: '#4ADE80',
    danger: '#F87171',
    warning: '#FBBF24',
    muted: '#94A3B8',
    border: '#24304A',
    card: '#151E2E',
    missedTint: '#3B2429',
    completedTint: '#1F3B2E',
    partiallyCompletedTint: '#3F3620',
    categoryFallback: '#94A3B8',
  },
  // "Forest Dark" — calm, natural, relaxing, easy on the eyes.
  deepForestDark: {
    text: '#E5EDE8',
    background: '#0B1210',
    tint: '#34D399',
    icon: '#91A39A',
    tabIconDefault: '#91A39A',
    tabIconSelected: '#34D399',
    success: '#4ADE80',
    danger: '#F87171',
    warning: '#FBBF24',
    muted: '#91A39A',
    border: '#223028',
    card: '#14201B',
    missedTint: '#3A2725',
    completedTint: '#1D3A2C',
    partiallyCompletedTint: '#3B3620',
    categoryFallback: '#91A39A',
  },
  // "Deep Teal" — modern, sophisticated, balanced and eye-friendly.
  midnightOceanDark: {
    text: '#E0F2F1',
    background: '#081416',
    tint: '#2DD4BF',
    icon: '#8FA7A8',
    tabIconDefault: '#8FA7A8',
    tabIconSelected: '#2DD4BF',
    success: '#6EE7B7',
    danger: '#FB7185',
    warning: '#FBBF24',
    muted: '#8FA7A8',
    border: '#1C3235',
    card: '#102326',
    missedTint: '#33262A',
    completedTint: '#17362E',
    partiallyCompletedTint: '#35301C',
    categoryFallback: '#8FA7A8',
  },
  // "Warm Charcoal" — warm, soft, comfortable for low-light environments.
  warmCharcoalDark: {
    text: '#E9E3DC',
    background: '#141312',
    tint: '#FBBF24',
    icon: '#A8A29E',
    tabIconDefault: '#A8A29E',
    tabIconSelected: '#FBBF24',
    success: '#86EFAC',
    danger: '#FCA5A5',
    warning: '#FB923C',
    muted: '#A8A29E',
    border: '#2E2B27',
    card: '#211F1D',
    missedTint: '#3A2723',
    completedTint: '#253A2C',
    partiallyCompletedTint: '#3F3420',
    categoryFallback: '#A8A29E',
  },
  // "Graphite + Purple" — premium, elegant, modern; suited to productivity apps.
  mutedPlumDark: {
    text: '#E8E8EC',
    background: '#111113',
    tint: '#A78BFA',
    icon: '#A1A1AA',
    tabIconDefault: '#A1A1AA',
    tabIconSelected: '#A78BFA',
    success: '#6EE7B7',
    danger: '#FB7185',
    warning: '#FBBF24',
    muted: '#A1A1AA',
    border: '#29292F',
    card: '#1C1C20',
    missedTint: '#3B2530',
    completedTint: '#1F3630',
    partiallyCompletedTint: '#3C3420',
    categoryFallback: '#A1A1AA',
  },
} as const;

export type ThemeName = keyof typeof Colors;

/** Whether each named theme is a light or dark palette (drives status bar, nav theme, system-preference resolution). */
export const ThemeScheme: Record<ThemeName, 'light' | 'dark'> = {
  softPaperLight: 'light',
  sageCalmLight: 'light',
  oceanMistLight: 'light',
  warmOatLight: 'light',
  lavenderHazeLight: 'light',
  slateNightDark: 'dark',
  deepForestDark: 'dark',
  midnightOceanDark: 'dark',
  warmCharcoalDark: 'dark',
  mutedPlumDark: 'dark',
};

export const THEME_LABELS: Record<ThemeName, string> = {
  softPaperLight: 'Soft Paper Light',
  sageCalmLight: 'Sage Calm Light',
  oceanMistLight: 'Ocean Mist Light',
  warmOatLight: 'Warm Oat Light',
  lavenderHazeLight: 'Lavender Haze Light',
  slateNightDark: 'Midnight Blue',
  deepForestDark: 'Forest Dark',
  midnightOceanDark: 'Deep Teal',
  warmCharcoalDark: 'Warm Charcoal',
  mutedPlumDark: 'Graphite + Purple',
};

/** Recommended defaults used to resolve the 'system' theme preference. */
export const DEFAULT_LIGHT_THEME: ThemeName = 'softPaperLight';
export const DEFAULT_DARK_THEME: ThemeName = 'slateNightDark';

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
