-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	full_name VARCHAR(100) NOT NULL CHECK (length(full_name) > 0),
	email VARCHAR(255) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	role VARCHAR(100),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);